#!/usr/bin/env bash
#
#  installer for akutils functions
#
#  Version 0.0.1 (Novermber, 13, 2015)
#
#  Copyright (c) 2015 Andrew Krohn
#
#  This software is provided 'as-is', without any express or implied
#  warranty. In no event will the authors be held liable for any damages
#  arising from the use of this software.
#
#  Permission is granted to anyone to use this software for any purpose,
#  including commercial applications, and to alter it and redistribute it
#  freely, subject to the following restrictions:
#
#  1. The origin of this software must not be misrepresented; you must not
#     claim that you wrote the original software. If you use this software
#     in a product, an acknowledgment in the product documentation would be
#     appreciated but is not required.
#  2. Altered source versions must be plainly marked as such, and must not be
#     misrepresented as being the original software.
#  3. This notice may not be removed or altered from any source distribution.
#

## Find home directory.
workdir=$(pwd)
cd
homedir=$(pwd)
cd $workdir

## Run install if .bashrc exists
if [[ -f "$homedir/.bashrc" ]]; then
	repodir="$( cd "$( dirname "$0" )" && pwd )"
	sourceline="source $repodir/akutils_resources/akutils_autocomplete"
	sourcecount=$(grep "$sourceline" ~/.bashrc | wc -l)
	if [[ "$sourcecount" == "0" ]]; then
	echo "
## Autocompletion for akutils commands.
$sourceline
" >> $homedir/.bashrc
		sourcecount=$(grep $sourceline ~/.bashrc | wc -l)
		if [[ "$sourcecount" == "0" ]]; then
		echo "
Unexpected problem.  akutils not installed.
		"
		elif [[ "$sourcecount" -ge "1" ]]; then
		echo "
akutils successfully installed.  Restart your terminal or run:
source ~/.bashrc
		"
		fi
	elif [[ "$sourcecount" -ge "1" ]]; then
	echo "
akutils is already installed.
	"
	fi
source $homedir/.bashrc
else
	echo "
No $homedir/.bashrc file found.  You may need to manually configure akutils.
	"
fi

exit 0
