#!/usr/bin/env bash
#
#  installer for akutils functions
#
#  Version 0.0.1 (Novermber, 13, 2015)
#
#  Copyright (c) 2015 Andrew Krohn
#
#  This software is provided 'as-is', without any express or implied
#  warranty. In no event will the authors be held liable for any damages
#  arising from the use of this software.
#
#  Permission is granted to anyone to use this software for any purpose,
#  including commercial applications, and to alter it and redistribute it
#  freely, subject to the following restrictions:
#
#  1. The origin of this software must not be misrepresented; you must not
#     claim that you wrote the original software. If you use this software
#     in a product, an acknowledgment in the product documentation would be
#     appreciated but is not required.
#  2. Altered source versions must be plainly marked as such, and must not be
#     misrepresented as being the original software.
#  3. This notice may not be removed or altered from any source distribution.
#

## Find home directory.
workdir=$(pwd)
cd
homedir=$(pwd)
cd $workdir
echo ""

## Run install steps if .bashrc exists
if [[ -f "$homedir/.bashrc" ]]; then
	repodir="$( cd "$( dirname "$0" )" && pwd )"
	sourceline="source $repodir/akutils_resources/akutils_autocomplete"
	sourcecount=$(grep "$sourceline" ~/.bashrc 2>/dev/null | wc -l)
	pathline="$repodir/scripts"
	pathcount=$(grep "$pathline" ~/.bashrc 2>/dev/null | wc -l)

	if [[ "$sourcecount" == "0" ]]; then
	echo "
## Autocompletion for akutils commands.
$sourceline
" >> $homedir/.bashrc

		sourcecount=$(grep $sourceline ~/.bashrc 2>/dev/null | wc -l)
		if [[ "$sourcecount" == "0" ]]; then
		echo "Unexpected problem. Command autocompletion not configured.
		"
		elif [[ "$sourcecount" -ge "1" ]]; then
		echo "Command autocompletion successfully configured for akutils.
		"
		fi

	elif [[ "$sourcecount" -ge "1" ]]; then
	echo "Command autocompletion already configured for akutils.
	"
	fi

	if [[ "$pathcount" == "0" ]]; then

		bashrcpathcount=$(grep "PATH=" ~/.bashrc 2>/dev/null | wc -l)
		if [[ "$bashrcpathcount" -ge "1" ]]; then
		sed -i "/PATH/s/\"$/:TARGET/" ~/.bashrc 2>/dev/null || true
		sed -i "/PATH/s|TARGET$|$repodir/scripts\"|" ~/.bashrc 2>/dev/null || true
		else
		echo "
## Add PATH variables here.
PATH=\"\$PATH:$repodir/scripts\"
" >> $homedir/.bashrc
		fi

		pathcount=$(grep $pathline ~/.bashrc 2>/dev/null | wc -l)
		if [[ "$pathcount" == "0" ]]; then
		echo "Unexpected problem. PATH to akutils scripts not configured.
		"
		elif [[ "$pathcount" -ge "1" ]]; then
		echo "Command PATH successfully configured for akutils.
		"
		fi

	elif [[ "$pathcount" -ge "1" ]]; then
	echo "Command PATH already configured for akutils.
	"
	fi

source $homedir/.bashrc

	sourcecount=$(grep "$sourceline" ~/.bashrc 2>/dev/null | wc -l)
	pathcount=$(grep "$pathline" ~/.bashrc 2>/dev/null | wc -l)

	if [[ "$sourcecount" -ge "1" && "$pathcount" -ge "1" ]]; then
	echo "akutils is properly configured. Restart your terminal or run:
source ~/.bashrc
	"
	else
	echo "Unexpected problem(s) encountered.
	"
		if [[ "$sourcecount" -eq "0" ]]; then
		echo "Command autocompletion not configured.
		"
		else
		echo "Command autocompletion is properly configured.
		"
		fi

		if [[ "$pathcount" -eq "0" ]]; then
		echo "Command PATH not configured.
		"
		else
		echo "Command PATH is properly configured.
		"
		fi
	fi

else
	echo "
No $homedir/.bashrc file found. You may need to manually configure akutils.
	"
fi

exit 0
